### ISSUE TITLE
Using Embedded browser with SwiftUI

### ISSUE THREAD

**Issue by jcombs-pointblue** [p2/OAuth2#334] opened 2020-02-10 20:14 UTC
So far I haven't been able to figure out how to use an embedded browser view for auth from a ContentView delegate. Does the API actually support this yet?

**Comment by jcombs-pointblue** [comment] 2020-04-13 22:46
Has anyoone else tried to figure this out?

**Comment by pollsmor** [comment] 2020-07-08 23:35
This is probably way late, but I found a fix:

`oauth2.authConfig.authorizeEmbedded = true`

 `oauth2.authConfig.authorizeContext = UIApplication.shared.windows[0].rootViewController`

**Comment by jcombs-pointblue** [comment] 2020-07-09 12:59
Not too, late at all! Thanks, hard to believe it was that simple

**Comment by cacaosteve** [comment] 2020-12-16 01:59
does this package actually support SwiftUI??? I don't see anything about that

**Comment by ossus-lib** [comment] 2021-01-02 10:16
The embedded browser shouldn't be used anymore because it technically allows the dev to get at username/password. As of iOS 12 ASWebAuthenticationSession is the way to go.

**Comment by dacastanaza** [comment] 2021-09-03 19:00
> does this package actually support SwiftUI??? I don't see anything about that

Hello
Yes my question also.
My app is being rejected at the review process because I was not using the embedded authentication session, but I am not able to make it work in my SwiftUI app.

Is there a way?

**Comment by dacastanaza** [comment] 2021-09-19 02:02
Hello
I was finally able to get the ASWebAuthenticationSession to work in SwiftUI. I had to change the presentationAnchor function in the OAuth2ASWebAuthenticationPresentationContextProvider in file OAuth2Authorizer+iOS.swift to this:

	public func presentationAnchor(for session: ASWebAuthenticationSession) -> ASPresentationAnchor {
		return ASPresentationAnchor()
	}

This works for my specific use case, but I think a better implementation for this function to support all (or most) scenarios would be something like this:

	public func presentationAnchor(for session: ASWebAuthenticationSession) -> ASPresentationAnchor {
		return context.view.window ?? ASPresentationAnchor()
	}

Hope this helps, since the issue is tagged as "wont fix", but maybe the fix is not that hard at all (but it took for me many failed attempts. :D )

**Comment by ossus-lib** [comment] 2021-09-21 06:14
This should be fixed in [3.5.2](https://github.com/p2/OAuth2/releases/tag/5.3.2) via #361 , can you check it works for you? You can set `oauth2.authConfig.authorizeContext` to either a UIViewController on ASPresentationAnchor.

**Closed by ossus-lib** 2021-09-21 06:14 UTC
Labels: wontfix

**Comment by dacastanaza** [comment] 2021-09-21 22:32
> This should be fixed in [3.5.2](https://github.com/p2/OAuth2/releases/tag/5.3.2) via #361 , can you check it works for you? You can set `oauth2.authConfig.authorizeContext` to either a UIViewController on ASPresentationAnchor.

Thanks
I had version 5.3.1, so even if I set oauth2.authConfig.authorizeContext to ASPresentationAnchor, it would fail, because the presentationAnchor has a guard validating if the authorizeContext is a UIViewController, so it always failed.
I had to clone the package and make the change to work with my project, so I then made some other changes specific to my project. I even implemented ASWebAuthenticationSession for macOS, which is not in 5.3.1 either, not sure if it is in the newest version.
