### ISSUE TITLE
Renew access token from refresh token

### ISSUE THREAD

**Issue by jonas-andersson-stratsys** [p2/OAuth2#18] opened 2015-04-17 07:15 UTC
How do I most easily implement so that I do not need to log in every time? I assume the framework supports so I can use hasUnexpiredAccessToken() to first check if accesstoken is ok, then if not, try to use refresh token to get a new unexpired access token.

What's the best way to do this?

Also do you recommend any way of storing the tokens on the device so they don't get cleared when closing the app?

**Comment by p2** [comment] 2015-04-18 00:22
So far there is no built-in way to refresh a token. I have just pushed a first version to the `develop` branch, can you take a look and try it out? You can use the following method. Call it and it will use the standard callbacks once it's done. Set `oauth.verbose = true` in a first, normal code flow so the refresh token gets logged, then build it in statically for testing purposes.

```swift
oauth2.verbose = true
oauth2.afterAuthorizeOrFailure = { wasFailure, error in
    ...
}
oauth2.refreshTokenWithRefreshToken("< refresh-token >")
```

To store the tokens you should use the keychain. Would be an idea to build this into the client...

**Comment by p2** [comment] 2015-04-20 01:57
Keychain integration is now built in, it's also on the `develop` branch still. It's all automatic, see the updated README (on the develop branch).

**Comment by jonas-andersson-stratsys** [comment] 2015-04-20 08:02
Awesome! Will try it out!

**Comment by kimdv** [comment] 2015-05-08 10:50
+1 to renew access token and keychain!

**Comment by kimdv** [comment] 2015-05-11 11:43
When i try to login i get this error: 
Failed to store tokens to keychain: The operation couldn’t be completed. (swift.keychain.error.domain error -25300.)

**Comment by p2** [comment] 2015-05-11 16:06
I have pushed some updates, the code has also changed. Can you try again after updating your code (see the `README`)? I was unable to reproduce your error but have changed quite a few things.

**Comment by kimdv** [comment] 2015-05-12 08:03
On iOS simulator 8.3 iPhone 6 i get this error
Failed to store tokens to keychain: The operation couldn’t be completed. (swift.keychain.error.domain error -25300.)

And i also get it when i use my iPhone 6

This is how i have implemented it. 

Before this develop version i used CocoaPods to implement it. I overwritten the files with the develop version. I also implemented SwiftKeychain via CocoaPods and used import SiftKeychain in the Oauth2.swift file

**Comment by p2** [comment] 2015-05-12 12:36
@kimdv You cannot use your own SwiftKeychain installation, I'm using a custom build to deal with the error you are getting. You can try also replacing the SwiftKeychain files (esp. `Keychain.swift`) with the ones referenced here until I push the whole implementation to CocoaPods.

**Comment by kimdv** [comment] 2015-05-12 14:06
@p2 it works fine now! 
Thanks!

**Comment by kimdv** [comment] 2015-05-14 20:49
Any idea when it will be released? :D

**Comment by p2** [comment] 2015-05-14 21:06
Need to do some more testing, I hope to get to it soon. :)

**Comment by alikazim** [comment] 2015-05-21 07:08
Hi, P2 
I have used the Develop branch.

Iam not getting the point how to refresh my access_token using the refresh token

after authentication I got this response

OAuth2: Handling redirect URL jamesappv2://oauth/callback?state=BD1E84B8&code=YhCXXXXLfXqF8YSvUHKmkvi
OAuth2: Successfully validated redirect URL
OAuth2: Authorizing against https://login.uber.com/oauth/token?redirect_uri=jamesappv2%3A%2F%2Foauth%2Fcallback&scope=request+history&grant_type=authorization_code&code=YhXXXXX3yLLfXqF8YXXXXXmkvi&client_secret=e5FXXXXX2w63qXXXXXXNh6BJaMawxo03W&client_id=fXfp78T5y2LOUo9vtKzobvMLvxQ1nUDO&state=A304A1CB
OAuth2: Exchanging code YhCbzEIeXXXXXLfXqF8YSvUHKmkvi with redirect jamesappv2://oauth/callback for access token from Optional("https://login.uber.com/oauth/token")
OAuth2: Did exchange code for access [true] and refresh [true] tokens
OAuth2: Storing tokens to keychain
Did authorize with parameters: [token_type: Bearer, expires_in: 2592000, access_token: 0sXlmXXXaW3RF2kXXXnivV7ciD2U, refresh_token: kBEXLXXXLUmaczmXXXCC, scope: request history, last_authenticated: 1432190567]

Note: The expires_in 2592000 (sec) which is equal to 30 days

I have the following things now

accessToken Optional("0sXlXXXXX3RF2kXXXV7ciD2U")
accessTokenExpiry Optional(2015-06-20 06:42:49 +0000)
authConfig OAuth2.OAuth2AuthConfig
refreshToken Optional("kBEXXXXSToLUmXXXXz8CC")

How can I use those to refresh the token.

**Comment by p2** [comment] 2015-05-21 15:01
Version `1.2.3` is now live on [CocoaPods](https://cocoapods.org/pods/p2.OAuth2). It includes support for the keychain and methods for refreshing the access token from refresh tokens (where available). The old methods still work but you will have to use the new `authorize()` method to get keychain and/or refresh token benefits, please [see the guide](https://github.com/p2/OAuth2#usage).

**Closed by p2** 2015-05-21 15:01 UTC
Labels: enhancement, question
